### ISSUE TITLE
Custom command > Run in Terminal doesn't run the command

### ISSUE THREAD

**Issue by louis77** [DevAlien/workspaces#23]
... it only opens the Terminal window:

![Peek 2020-09-01 21-04](https://user-images.githubusercontent.com/1240462/91894990-cbffa600-ec96-11ea-9b97-ca7dc98bc3c6.gif)

**Comment by DevAlien** [comment]
Maybe flatpak-spawn needs some flags to run in terminal. I'm investigating

**Comment by matfantinel** [comment]
For the record, I'm having a similar issue with a non-Flatpak version (I installed from AppCenter).

But I can actually get some commands to work. For example, I run "mongod" to start the MongoDB service and it works. Same for "htop". However, I can't run some aliases (for example "graphics" in my screencast below), and more complex commands that start with "cd ~/Pictures" for example, that throw out `Failed to execute child process “cd” (No such file or directory)`.

![Screen record from 2020-09-09 16 04 10](https://user-images.githubusercontent.com/24247035/92642330-68890000-f2b6-11ea-8af7-70901df267f7.gif)


If you think this might be a different problem, I can open a different issue.

**Comment by DevAlien** [comment]
@matfantinel Sorry I missed this. We made a fix for this, would be great if you could give it a go. It is in the develop branch.

**Comment by matfantinel** [comment]
So, after some evaluation and debugging with @DevAlien , we noticed that `x-terminal-emulator -x my-alias` and `x-terminal-emulator -e "my-alias"` weren't working with aliases, [because non-interactive commands do not have access to aliases defined in .bashrc](https://unix.stackexchange.com/questions/1496/why-doesnt-my-bash-script-recognize-aliases).

On my local tests, running `x-terminal-emulator -e 'bash -i -c "my-alias"'` worked. It basically the -i flag means the terminal will be interactive, which makes the aliases load. It fixed my use case, and didn't break anything apparently.

**Comment by DevAlien** [comment]
If someone wants something special like that should do it on its own for the moment, not everybody uses bash etc. BUt commands should run better now. The issue with aliases stays there though. This is ready for 3.1 https://github.com/DevAlien/workspaces/issues/32

**Comment by matfantinel** [comment]
That's fine. As soon as the change that changes -c to -e comes out, I can add `bash -i -c "my-alias"` part myself on the command.
